@localhost=localhost:4004/odata/v4/main
@product_id1=16481621-8d52-425b-ae38-8f816e87682f
@product_id2=14195958-1289-41ea-9d06-865a9eaf09b5

###

GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic joaozinho:abcd1234
{
    "id": "123",
    "customer_id": "29054544-234b-4ee7-9557-9d5c75e4b03b",
    "totalAmount": 398,
    "items": [
        {
            "header_id": "123",
            "id": "11",
            "product_id": "{{product_id2}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "header_id": "123",
            "id": "21",
            "product_id": "{{product_id2}}",
            "quantity": 15,
            "price": 2.98
        }
    ]
}

###

DELETE http://{{localhost}}/SalesOrderHeaders(d4105ea2-81d3-4469-b64c-e8c9d8010f16)
Content-Type: application/json



###

# Buscando dados com $search

GET http://{{localhost}}/SalesOrderHeaders?$search=6iyw1
Content-Type: application/json